server {
    listen 80;
    server_name _;

    # Главная страница — заглушка
    location / {
        return 200 'OK';
        add_header Content-Type text/plain;
    }

    # pgAdmin — доступен по /pgadmin/
    location /pgadmin/ {
        proxy_pass http://pgadmin:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Script-Name /pgadmin;
    }
}
